# Generated by Django 4.1.3 on 2022-11-21 20:28

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('product_card', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcard',
            name='descrption',
            field=tinymce.models.HTMLField(),
        ),
    ]
