# Generated by Django 4.1.3 on 2022-11-21 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0002_alter_theme_favicon_alter_theme_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='favicon',
            field=models.FileField(blank=True, help_text='(.ico|.png|.gif - 16x16|32x32 px)', upload_to='static/admin_interface/favicon/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'ico', 'jpg', 'jpeg', 'png', 'svg'])], verbose_name='favicon'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='logo',
            field=models.FileField(blank=True, help_text='Leave blank to use the default Django logo', upload_to='static/admin_interface/logo/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['gif', 'jpg', 'jpeg', 'png', 'svg'])], verbose_name='logo'),
        ),
    ]
