# Generated by Django 4.1.3 on 2022-11-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_interface', '0004_alter_theme_favicon_alter_theme_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='facebook_url',
            field=models.CharField(default='', max_length=200, verbose_name='FaceBook Url'),
        ),
        migrations.AddField(
            model_name='theme',
            name='linked_url',
            field=models.CharField(default='', max_length=200, verbose_name='Linkedin Url'),
        ),
        migrations.AddField(
            model_name='theme',
            name='whatsapp_url',
            field=models.CharField(default='', max_length=200, verbose_name='Whatsapp Url'),
        ),
    ]
